name: claro_travel_hotel_makassar
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2 # Your current Dart SDK version

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  http: ^1.2.0
  path: ^1.8.3
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.6.0

  # WebView package - ONLY ONE ENTRY
  webview_flutter: ^4.2.4

  # Database packages
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0

  intl: ^0.17.0 # atau versi terbaru

  # Permissions
  permission_handler: ^11.3.0

  image_picker: ^1.0.4
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2 # Tambahkan ini
  cached_network_image: ^3.4.1

  smooth_page_indicator: ^1.1.0
  flutter_image_slideshow: ^0.1.6

  url_launcher: ^6.1.12
  shimmer: ^2.0.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
